## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
# import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(["EIN", "NAME"],axis = 1)

In [8]:
cols = application_df.dtypes == object
cols_list = cols[cols].index.tolist()
cols_list

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

application_types_to_replace = application_df["APPLICATION_TYPE"].value_counts()[application_df["APPLICATION_TYPE"].value_counts() <= 500].index.tolist()
application_types_to_replace

# Replace in dataframe
for app_type in application_types_to_replace:
    application_df["APPLICATION_TYPE"] = application_df["APPLICATION_TYPE"].replace(app_type,"Other")

# Check to make sure binning was successful
application_df["APPLICATION_TYPE"].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
application_df["CLASSIFICATION"].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df["CLASSIFICATION"].value_counts()[application_df["CLASSIFICATION"].value_counts() > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = application_df["CLASSIFICATION"].value_counts()[application_df["CLASSIFICATION"].value_counts() <= 1000].index.tolist()
classifications_to_replace
# Replace in dataframe
for cls_type in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls_type,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
ask_to_replace = application_df["ASK_AMT"][application_df["ASK_AMT"] > 5000].tolist()

for ask in ask_to_replace:
    application_df['ASK_AMT'] = application_df['ASK_AMT'].replace(ask,"Other")

application_df["ASK_AMT"].value_counts()

5000     25398
Other     8901
Name: ASK_AMT, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df.dtypes

df = application_df.drop(["APPLICATION_TYPE", "AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION",
                                            "INCOME_AMT", "SPECIAL_CONSIDERATIONS", "ASK_AMT"], axis=1)

dummies_df = pd.get_dummies(application_df[["APPLICATION_TYPE", "AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION",
                                            "INCOME_AMT", "SPECIAL_CONSIDERATIONS", "ASK_AMT"]])

numeric_app_df = pd.concat([df, dummies_df], axis=1)
numeric_app_df.head()

,STATUS,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,ASK_AMT_5000,ASK_AMT_Other
0,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
2,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0
3,1,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
4,1,1,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,1,0,0,1

In [12]:
# Split our preprocessed data into our features and target arrays
X = numeric_app_df.drop("IS_SUCCESSFUL", axis = 1)
y = numeric_app_df["IS_SUCCESSFUL"]
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train.iloc[0])
layer1=80
layer2=50
layer3=30
layer4=10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer2, activation="relu")
)

# Third hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer3, activation="relu")
)
# Fourth hidden layer
nn.add(
    tf.keras.layers.Dense(units=layer4, activation="relu")
)
# Output layer
nn.add(
    tf.keras.layers.Dense(units=1, activation="sigmoid")
)

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3600

 dense_1 (Dense)             (None, 50)                4050

 dense_2 (Dense)             (None, 30)                1530

 dense_3 (Dense)             (None, 10)                310

 dense_4 (Dense)             (None, 1)                 11

=================================================================
Total params: 9501 (37.11 KB)
Trainable params: 9501 (37.11 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5733 - accuracy: 0.7216
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5537 - accuracy: 0.7311
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7325
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7326
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7341
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7338
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7341
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7347
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7354
Epoch 10/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5437 - accuracy: 0.7372
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7362
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7368
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7376
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7367
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7374
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7382
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7385
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7380
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7369
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7389
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7377
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7389
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7385
Epoch 24/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5388 - accuracy: 0.7396
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7386
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7397
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7393
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7391
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7396
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7387
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.7394
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7394
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7397
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7399
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7402
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7408
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7386
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7392
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7407
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7401
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7405
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7395
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7414
Epoch 44/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5352 - accuracy: 0.7402
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7408
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7406
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7402
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7404
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7408
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5343 - accuracy: 0.7414
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7401
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7396
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7411
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7416
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7411
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7410
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5341 - accuracy: 0.7416
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5345 - accuracy: 0.7410
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7414
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7411
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7416
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7410
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7413
Epoch 64/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5329 - accuracy: 0.7414
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7415
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7412
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7424
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7424
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7416
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7418
Epoch 71/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5329 - accuracy: 0.7418
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7420
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7421
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7423
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7414
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7419
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7425
Epoch 78/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5321 - accuracy: 0.7422
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7423
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7412
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7420
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7419
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7422
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7413
Epoch 85/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5313 - accuracy: 0.7421
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7416
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7422
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7421
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5314 - accuracy: 0.7421
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7424
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.7423
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5308 - accuracy: 0.7423
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7430
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7420
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7423
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7419
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7425
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5316 - accuracy: 0.7429
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7428
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7423

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5761 - accuracy: 0.7250 - 522ms/epoch - 2ms/step
Loss: 0.5760893821716309, Accuracy: 0.7250145673751831

In [21]:
# Export our model to HDF5 file
from google.colab import drive
drive.mount('/content/drive')

nn.save("/content/drive/My Drive/AlphabetSoupCharity_Optimization.hdf5")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(